encoding: UTF-8

permalink: /:year/:month/:day/:title.html
paginate: 8
markdown: kramdown

kramdown:
  input: GFM

highlighter: pygments
pygments: true

# 作者信息
author: 
  name: 陶哓然
  email: initialran@gmail.com
  link: http://lemonjing.github.io/
  weibo: http://weibo.com/u/1662536394
  github: https://github.com/lemonjing
  github_username:  lemonjing
  zhihu: https://www.zhihu.com/people/tao-xiao-xiao-99
  weibo_username:  _NoThankYou

# 站点信息
title: 绾青丝
description: 
 If,<br>for example,<br>you come at four o'clock in the afternoon,<br>then at three o'clock I shall begin to be happy.
rss_url: /feed.xml

# gavatar头像及Favicon
gavatar : /assets/img/gavatar.png
favicon : /assets/img/favicon.ico

# disqus 设置
#disqus:
#  shortname: blademastercoder

#profile 个人信息

profile_desc : 绾青丝<br>挽情思<br>任风雨飘摇<br>人生不惧<br><br>

# 首页除了最新文章外显示分类
cates: 
- Essay
# - Python
# - OpenStack

# 中文本地化
locals: 
   newest : 最新文章
